export interface SpecializedProduct {
  id: string;
  name: string;
  icon: string;
  description: string;
  model: string;
  category: string;
  url: string;
}

export const specializedProducts: SpecializedProduct[] = [
  {
    id: "a1",
    name: "Growth Advisory",
    icon: "??",
    description: "Business development and market analysis",
    model: "Claude 3.5 Sonnet",
    category: "business",
    url: "https://mornhub.net",
  },
  {
    id: "b1",
    name: "Interview/Job",
    icon: "??",
    description: "Career development and interview prep",
    model: "GPT-4o Mini",
    category: "career",
    url: "https://mornhub.pics/interview",
  },
  {
    id: "l1",
    name: "AI Lawyer",
    icon: "??",
    description: "Legal consultation and document review",
    model: "Claude 3.5 Sonnet",
    category: "legal",
    url: "https://mornhub.pics/lawyer",
  },
  {
    id: "c1",
    name: "AI Coder",
    icon: "??",
    description: "Advanced coding assistant",
    model: "CodeLlama",
    category: "development",
    url: "https://mornhub.pics/coder",
  },
  {
    id: "h1",
    name: "Multi-GPT",
    icon: "??",
    description: "Orchestrates multiple AI models to solve complex tasks",
    model: "GPT-4o Mini",
    category: "productivity",
    url: "https://mornhub.pics/multigpt",
  },
  {
    id: "w1",
    name: "Content Generation",
    icon: "??",
    description: "Creative content creation",
    model: "GPT-4o Mini",
    category: "creative",
    url: "https://mornhub.pics",
  },
  {
    id: "e1",
    name: "Medical Advice",
    icon: "??",
    description: "Health consultation AI",
    model: "Claude 3.5 Sonnet",
    category: "health",
    url: "https://mornhub.pics/medical",
  },
  {
    id: "d1",
    name: "Content Detection",
    icon: "???",
    description: "Fake content verification",
    model: "Claude 3.5 Sonnet",
    category: "security",
    url: "https://mornhub.pics/detect",
  },
  {
    id: "z1",
    name: "AI Protection",
    icon: "??",
    description: "AI safety and security",
    model: "Claude 3.5 Sonnet",
    category: "security",
    url: "https://mornhub.pics/protection",
  },
  {
    id: "q1",
    name: "AI Teacher",
    icon: "??",
    description: "Personalized learning system",
    model: "Claude 3.5 Sonnet",
    category: "education",
    url: "https://mornhub.pics/teacher",
  },
  {
    id: "n1",
    name: "AI Entertainment Advisor",
    icon: "??",
    description: "Movie, music, and entertainment recommendations",
    model: "GPT-4o Mini",
    category: "entertainment",
    url: "https://mornhub.pics/entertainment",
  },
  {
    id: "o1",
    name: "Housing",
    icon: "??",
    description: "Real estate and accommodation",
    model: "Claude 3.5 Sonnet",
    category: "lifestyle",
    url: "https://mornhub.homes",
  },
  {
    id: "t1",
    name: "Fashion",
    icon: "??",
    description: "Personalized styling advice",
    model: "GPT-4o Mini",
    category: "lifestyle",
    url: "https://mornhub.pics/fashion",
  },
  {
    id: "u1",
    name: "Food & Dining",
    icon: "???",
    description: "Restaurant and food discovery",
    model: "Claude 3.5 Sonnet",
    category: "food",
    url: "https://mornhub.pics/food",
  },
  {
    id: "r1",
    name: "Travel Planning",
    icon: "??",
    description: "Intelligent travel assistance",
    model: "GPT-4o Mini",
    category: "travel",
    url: "https://mornhub.pics/travel",
  },
  {
    id: "s1",
    name: "Product Search",
    icon: "??",
    description: "Smart product recommendations",
    model: "Claude 3.5 Sonnet",
    category: "shopping",
    url: "https://mornhub.pics/search",
  },
  {
    id: "p1",
    name: "Person Matching",
    icon: "??",
    description: "Professional and personal matching",
    model: "GPT-4o Mini",
    category: "social",
    url: "https://mornhub.lat",
  },
];
