/**
 * Localization texts for MornGPT
 */

export const translations = {
  en: {
    placeholder: "Start a conversation with MornGPT...",
    thinking: "Thinking...",
    deepThinking: "Deep thinking in progress...",
    newChat: "New Chat",
    general: "General",
    generalModelTitle: "General Model",
    generalModelDesc: "Auto select AI assistant for general conversations",
    guestUser: "Guest User",
    login: "Login",
    signOut: "Sign Out",
    setting: "Setting",
    share: "Share",
    copy: "Copy",
    delete: "Delete",
    deepThinkingBtn: "Deep Thinking",
    creativeIdeasBtn: "Creative Ideas",
    analyzeBtn: "Analyze",
    problemSolveBtn: "Problem Solve",
    uploadFiles: "Upload files",
    send: "Send",
    copySelection: "Copy selected text",
    deleteSelection: "Delete selected text",
    uploadAudioFile: "Upload audio file",
    startVoiceRecording: "Start voice recording",
    stopVoiceRecording: "Stop voice recording",
    stopProVoiceChat: "Stop Pro voice chat",
    stopProVideoChat: "Stop Pro video chat",
    resetVoiceRecording: "Reset voice recording (if stuck)",
    cameraUnavailable: "Camera not available in this browser/device.",
    cameraOpen: "Open camera",
    cameraClose: "Close camera",
    locationAdded: "Location added - click to refresh",
    getLocation: "Get current location",
    switchToLight: "Switch to light mode",
    switchToDark: "Switch to dark mode",
    navigateConversation: "Navigate conversation",
    poweredBy: "Powered by",
    noChatSelected: "No chat selected",
    noConversationToShare: "No conversation to share",
    signUpToShare: "Sign up to share conversations",
    shareConversation: "Share conversation",
    shareGeneratingLink: "Generating share link...",
    shareLinkLabel: "Share Link",
    shareLinkPlaceholder: "Share link will appear here...",
    shareSecretKeyLabel: "Secret Key",
    shareSecretKeyPlaceholder: "Secret key will appear here...",
    shareMakePublic: "Make conversation discoverable (public)",
    shareHowTo: "How to share:",
    sharePublicDescription: "This conversation is public. Anyone with the link can access it.",
    sharePrivateStep1: "Copy the share link above",
    sharePrivateStep2: "Share the secret key with your recipient",
    sharePrivateStep3: "They need both the link and secret key to access",
    shareToSocial: "Share to Social Media",
    shareOnTwitter: "Share on Twitter",
    shareOnFacebook: "Share on Facebook",
    shareOnLinkedIn: "Share on LinkedIn",
    shareOnWhatsApp: "Share on WhatsApp",
    shareOnTelegram: "Share on Telegram",
    shareOnReddit: "Share on Reddit",
    shareOnDiscord: "Share on Discord",
    shareViaEmail: "Share via Email",
    shareOnSlack: "Share on Slack",
    shareOnInstagram: "Copy for Instagram",
    generateNewKey: "Generate New Key",
    proVoiceChat: "Pro voice chat",
    proVideoChat: "Pro video chat",
    proVoiceError: "Failed to access microphone. Please check permissions.",
    proVideoError: "Failed to access camera and microphone. Please check permissions.",
    cameraAccessFailed: "Failed to access camera. Please check permissions and device availability.",
    guestSessionExpired: "Your guest session has expired due to inactivity. Your conversations have been cleared.",
    textCopied: "Text copied to clipboard",
    textDeleted: "Text deleted",
    characters: "chars",
    dragToResize: "Drag to resize",
    shortcutsActive: "Shortcuts Active",
    shortcutsDisabled: "Shortcuts Disabled",
    enabled: "Enabled",
    disabled: "Disabled",
    newChatInGeneral: "New Chat in General",
    multiGPTDeepThinking: "Multi-GPT Deep Thinking",
    poweredByModel: "Powered by {model}",
    rename: "Rename",
    deleteChat: "Delete Chat",
    exportChat: "Export Chat",
    settings: "Settings",
    shortcuts: "Shortcuts",
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    sound: "Sound",
    autoSave: "Auto Save",
    errorLoadingShared: "Error loading shared conversation. The link may be invalid or expired.",
    sharedConversationLoaded: 'Shared conversation loaded: "{title}" by {author}',
    attachedFiles: "Attached Files",
    maximumFilesReached: "Maximum {count} files reached. Remove some files first.",
    uploading: "Uploading...",
    uploadFilesMax: "Upload files (max {count}, {size}MB total)",
    uploadFilesMaxCount: "Upload files (max {count})",
    selectModel: "Select Model",
    external: "External",
    mornGPT: "MornGPT",
    appName: "MornGPT",
    newMornGPTChat: "New MornGPT Chat",
    beSpecific: "Be specific about your goals",
    chooseSpecialized: "Choose specialized MornGPT models",
    uploadFilesWith: "Upload files with",
    useCtrlEnter: "Use Ctrl/Cmd + Enter",
    download: "Download",
    bookmark: "Bookmark",
    bookmarked: "Bookmarked",
    removeBookmark: "Remove bookmark",
    copyResponse: "Copy response",
    shareResponse: "Share response",
    downloadResponse: "Download response",
    bookmarkMessage: "Bookmark message",
    heroTagline: "Advanced AI models at your fingertips",
    searchConversations: "Search conversations...",
    searchBookmarks: "Search bookmarks...",
    searchPrompts: "Search prompts...",
    recentPromptsHistory: "Recent Prompts History",
    noPromptsFound: "No prompts found",
    noRecentPrompts: "No recent prompts",
    conversationTab: "Conversation",
    bookmarksTab: "Bookmarks",
    promptsTab: "Prompts",
    jumpToConversation: "Jump to Conversation Section",
    noConversationsFound: "No conversations found",
    noConversationsYet: "No conversations yet",
    youLabel: "You",
    aiLabel: "AI",
    bookmarkedMessages: "Bookmarked Messages",
    exportBookmarks: "Export bookmarks",
    importBookmarks: "Import bookmarks",
    createFolder: "Create new folder",
    noBookmarksFound: "No bookmarks found",
    noBookmarksYet: "No bookmarked messages yet",
    settingsTitle: "Settings",
    themeLabel: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "Auto",
    languageLabel: "Language",
    languageEnglish: "English",
    languageChinese: "Chinese",
    notificationsLabel: "Notifications",
    soundLabel: "Sound Enabled",
    autoSaveLabel: "Auto Save",
    sendHotkeyLabel: "Send Hotkey",
    enterOption: "Enter",
    shiftEnterOption: "Shift + Enter",
    ctrlEnterOption: "Ctrl + Enter",
    cmdEnterOption: "Cmd + Enter",
    showAds: "Show Ads",
    hideAds: "Hide Ads",
    close: "Close",
    downloadApps: "Download Apps",
    searchChats: "Search chats...",
    account: "Account",
    profileSubtitle: "Your profile & subscription",
    username: "Username",
    save: "Save",
    cancel: "Cancel",
    turnOffAds: "Turn Off Ads",
    turnOnAds: "Turn On Ads",
    themeDescription: "Choose your preferred theme",
    languageDescription: "Choose your preferred language",
    fontFamily: "Font Family",
    fontFamilyDescription: "Choose your preferred font",
    fontSize: "Font Size",
    fontSizeDescription: "Choose your preferred size",
    hotkeysTitle: "Hotkeys",
    hotkeysDescription: "Customize keyboard shortcuts",
    billing: "Billing",
    billingDescription: "Manage subscription & payments",
    proFeatureOnly: "Pro feature - upgrade to enable",
    privacy: "Privacy",
    privacyDescription: "Security & account protection",
    support: "Support",
    supportDescription: "Get help & contact us",
  },
  zh: {
    placeholder: "开始与 MornGPT 对话...",
    thinking: "思考中...",
    deepThinking: "深度思考进行中...",
    newChat: "新对话",
    general: "通用",
    generalModelTitle: "General Model",
    generalModelDesc: "自动选择适合日常对话的AI助手",
    guestUser: "访客用户",
    login: "登录",
    signOut: "退出登录",
    setting: "设置",
    share: "分享",
    copy: "复制",
    delete: "删除",
    deepThinkingBtn: "深度思考",
    creativeIdeasBtn: "创意想法",
    analyzeBtn: "分析",
    problemSolveBtn: "问题解决",
    uploadFiles: "上传文件",
    send: "发送",
    copySelection: "复制选中文本",
    deleteSelection: "删除选中文本",
    uploadAudioFile: "上传音频文件",
    startVoiceRecording: "开始语音录制",
    stopVoiceRecording: "停止语音录制",
    stopProVoiceChat: "结束专业语音通话",
    stopProVideoChat: "结束专业视频通话",
    resetVoiceRecording: "录制异常时重置",
    cameraUnavailable: "当前设备/浏览器不支持摄像头",
    cameraOpen: "开启摄像头",
    cameraClose: "关闭摄像头",
    locationAdded: "已添加定位 - 点击重新获取",
    getLocation: "获取当前位置",
    switchToLight: "切换到浅色模式",
    switchToDark: "切换到深色模式",
    navigateConversation: "浏览对话记录",
    poweredBy: "由",
    noChatSelected: "未选择对话",
    noConversationToShare: "没有可分享的对话",
    signUpToShare: "注册以分享对话",
    shareConversation: "分享对话",
    shareGeneratingLink: "正在生成分享链接...",
    shareLinkLabel: "分享链接",
    shareLinkPlaceholder: "分享链接生成后将显示在此",
    shareSecretKeyLabel: "访问密钥",
    shareSecretKeyPlaceholder: "密钥生成后将显示在此",
    shareMakePublic: "将对话设为公开可发现",
    shareHowTo: "如何分享：",
    sharePublicDescription: "该对话为公开状态，持有链接的任何人都可访问。",
    sharePrivateStep1: "复制上方分享链接",
    sharePrivateStep2: "将访问密钥发给接收者",
    sharePrivateStep3: "对方需同时拥有链接和密钥才能访问",
    shareToSocial: "分享到社交平台",
    shareOnTwitter: "分享到 Twitter",
    shareOnFacebook: "分享到 Facebook",
    shareOnLinkedIn: "分享到 LinkedIn",
    shareOnWhatsApp: "分享到 WhatsApp",
    shareOnTelegram: "分享到 Telegram",
    shareOnReddit: "分享到 Reddit",
    shareOnDiscord: "分享到 Discord",
    shareViaEmail: "通过邮箱分享",
    shareOnSlack: "分享到 Slack",
    shareOnInstagram: "复制用于 Instagram",
    generateNewKey: "生成新密钥",
    proVoiceChat: "专业语音通话",
    proVideoChat: "专业视频通话",
    proVoiceError: "无法访问麦克风，请检查权限设置。",
    proVideoError: "无法访问摄像头和麦克风，请检查权限设置。",
    cameraAccessFailed: "无法访问摄像头，请检查权限或设备可用性。",
    guestSessionExpired: "由于不活动，您的访客会话已过期。您的对话已被清除。",
    textCopied: "文本已复制到剪贴板",
    textDeleted: "文本已删除",
    characters: "字符",
    dragToResize: "拖拽调整大小",
    shortcutsActive: "快捷键已启用",
    shortcutsDisabled: "快捷键已禁用",
    enabled: "已启用",
    disabled: "已禁用",
    newChatInGeneral: "在通用中新建对话",
    multiGPTDeepThinking: "多GPT深度思考",
    poweredByModel: "由 {model} 提供支持",
    rename: "重命名",
    deleteChat: "删除对话",
    exportChat: "导出对话",
    settings: "设置",
    shortcuts: "快捷键",
    theme: "主题",
    language: "语言",
    notifications: "通知",
    sound: "声音",
    autoSave: "自动保存",
    errorLoadingShared: "加载共享对话时出错。链接可能无效或已过期。",
    sharedConversationLoaded: '已加载共享对话："{title}" 由 {author} 创建',
    attachedFiles: "附件文件",
    maximumFilesReached: "已达到最大文件数 {count}。请先删除一些文件。",
    uploading: "上传中...",
    uploadFilesMax: "上传文件（最多 {count} 个，总计 {size}MB）",
    uploadFilesMaxCount: "上传文件（最多 {count} 个）",
    selectModel: "选择模型",
    external: "外部",
    mornGPT: "MornGPT",
    appName: "MornGPT",
    newMornGPTChat: "新建 MornGPT 对话",
    beSpecific: "明确您的目标",
    chooseSpecialized: "选择专门的 MornGPT 模型",
    uploadFilesWith: "上传文件",
    useCtrlEnter: "使用 Ctrl/Cmd + Enter",
    download: "下载",
    bookmark: "收藏",
    bookmarked: "已收藏",
    removeBookmark: "取消收藏",
    copyResponse: "复制回复",
    shareResponse: "分享回复",
    downloadResponse: "下载回复",
    bookmarkMessage: "收藏消息",
    heroTagline: "高级 AI 模型触手可及",
    searchConversations: "搜索对话...",
    searchBookmarks: "搜索书签...",
    searchPrompts: "搜索提示词...",
    recentPromptsHistory: "最近提示历史",
    noPromptsFound: "未找到提示",
    noRecentPrompts: "暂无提示历史",
    conversationTab: "对话",
    bookmarksTab: "书签",
    promptsTab: "提示词",
    jumpToConversation: "跳转到对话位置",
    noConversationsFound: "未找到对话",
    noConversationsYet: "还没有对话",
    youLabel: "你",
    aiLabel: "AI",
    bookmarkedMessages: "已收藏消息",
    exportBookmarks: "导出书签",
    importBookmarks: "导入书签",
    createFolder: "新建文件夹",
    noBookmarksFound: "未找到书签",
    noBookmarksYet: "还没有收藏的消息",
    settingsTitle: "设置",
    themeLabel: "主题",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    languageLabel: "语言",
    languageEnglish: "英语",
    languageChinese: "中文",
    notificationsLabel: "通知",
    soundLabel: "声音",
    autoSaveLabel: "自动保存",
    sendHotkeyLabel: "发送快捷键",
    enterOption: "回车",
    shiftEnterOption: "Shift + Enter",
    ctrlEnterOption: "Ctrl + Enter",
    cmdEnterOption: "Cmd + Enter",
    showAds: "显示广告",
    hideAds: "隐藏广告",
    close: "关闭",
    downloadApps: "下载客户端",
    searchChats: "搜索对话...",
    account: "账户",
    profileSubtitle: "个人资料与订阅",
    username: "用户名",
    save: "保存",
    cancel: "取消",
    turnOffAds: "关闭广告",
    turnOnAds: "打开广告",
    themeDescription: "选择你偏好的主题",
    languageDescription: "选择你偏好的语言",
    fontFamily: "字体",
    fontFamilyDescription: "选择偏好的字体",
    fontSize: "字号",
    fontSizeDescription: "选择偏好的字号",
    hotkeysTitle: "快捷键",
    hotkeysDescription: "自定义键盘快捷键",
    billing: "账单与订阅",
    billingDescription: "管理订阅与支付",
    proFeatureOnly: "Pro 专属功能 - 升级后可用",
    privacy: "隐私与安全",
    privacyDescription: "安全与账号保护",
    support: "支持",
    supportDescription: "获取帮助与联系我们",
  },
};

export type TranslationKey = keyof typeof translations.en;

// 国内版移动端品牌名
const DOMESTIC_MOBILE_BRAND = "晨佑AI平台";

export function getLocalizedText(key: TranslationKey, language: string, useDomesticMobileBrand = false): string {
  const lang = language as keyof typeof translations;
  let text = translations[lang]?.[key] || translations.en[key] || key;

  // 国内版移动端替换 MornGPT 为 晨佑AI平台
  if (useDomesticMobileBrand && typeof text === "string") {
    text = text.replace(/MornGPT/g, DOMESTIC_MOBILE_BRAND);
  }

  return text;
}

export function createLocalizedTextGetter(language: string, useDomesticMobileBrand = false) {
  return (key: TranslationKey) => getLocalizedText(key, language, useDomesticMobileBrand);
}
