/**
 * Localization texts for MornGPT
 */

export const translations = {
  en: {
    placeholder: "Start a conversation with MornGPT...",
    thinking: "Thinking...",
    deepThinking: "Deep thinking in progress...",
    newChat: "New Chat",
    general: "General",
    guestUser: "Guest User",
    login: "Login",
    signOut: "Sign Out",
    setting: "Setting",
    share: "Share",
    copy: "Copy",
    delete: "Delete",
    deepThinkingBtn: "Deep Thinking",
    creativeIdeasBtn: "Creative Ideas",
    analyzeBtn: "Analyze",
    problemSolveBtn: "Problem Solve",
    uploadFiles: "Upload files",
    send: "Send",
    poweredBy: "Powered by",
    noChatSelected: "No chat selected",
    noConversationToShare: "No conversation to share",
    signUpToShare: "Sign up to share conversations",
    shareConversation: "Share conversation",
    guestSessionExpired: "Your guest session has expired due to inactivity. Your conversations have been cleared.",
    textCopied: "Text copied to clipboard",
    textDeleted: "Text deleted",
    characters: "chars",
    dragToResize: "Drag to resize",
    shortcutsActive: "Shortcuts Active",
    shortcutsDisabled: "Shortcuts Disabled",
    enabled: "Enabled",
    disabled: "Disabled",
    newChatInGeneral: "New Chat in General",
    multiGPTDeepThinking: "Multi-GPT Deep Thinking",
    poweredByModel: "Powered by {model}",
    rename: "Rename",
    deleteChat: "Delete Chat",
    exportChat: "Export Chat",
    settings: "Settings",
    shortcuts: "Shortcuts",
    theme: "Theme",
    language: "Language",
    notifications: "Notifications",
    sound: "Sound",
    autoSave: "Auto Save",
    errorLoadingShared: "Error loading shared conversation. The link may be invalid or expired.",
    sharedConversationLoaded: 'Shared conversation loaded: "{title}" by {author}',
    attachedFiles: "Attached Files",
    maximumFilesReached: "Maximum {count} files reached. Remove some files first.",
    uploading: "Uploading...",
    uploadFilesMax: "Upload files (max {count}, {size}MB total)",
    selectModel: "Select Model",
    external: "External",
    mornGPT: "MornGPT",
    beSpecific: "Be specific about your goals",
    chooseSpecialized: "Choose specialized MornGPT models",
    uploadFilesWith: "Upload files with",
    useCtrlEnter: "Use Ctrl/Cmd + Enter",
    download: "Download",
    bookmark: "Bookmark",
    bookmarked: "Bookmarked",
    removeBookmark: "Remove bookmark",
    copyResponse: "Copy response",
    shareResponse: "Share response",
    downloadResponse: "Download response",
    bookmarkMessage: "Bookmark message",
    heroTagline: "Advanced AI models at your fingertips",
    searchConversations: "Search conversations...",
    searchBookmarks: "Search bookmarks...",
    searchPrompts: "Search prompts...",
    recentPromptsHistory: "Recent Prompts History",
    noPromptsFound: "No prompts found",
    noRecentPrompts: "No recent prompts",
    conversationTab: "Conversation",
    bookmarksTab: "Bookmarks",
    promptsTab: "Prompts",
    jumpToConversation: "Jump to Conversation Section",
    noConversationsFound: "No conversations found",
    noConversationsYet: "No conversations yet",
    youLabel: "You",
    aiLabel: "AI",
    bookmarkedMessages: "Bookmarked Messages",
    exportBookmarks: "Export bookmarks",
    importBookmarks: "Import bookmarks",
    createFolder: "Create new folder",
    noBookmarksFound: "No bookmarks found",
    noBookmarksYet: "No bookmarked messages yet",
    settingsTitle: "Settings",
    themeLabel: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "Auto",
    languageLabel: "Language",
    languageEnglish: "English",
    languageChinese: "Chinese",
    notificationsLabel: "Notifications",
    soundLabel: "Sound Enabled",
    autoSaveLabel: "Auto Save",
    sendHotkeyLabel: "Send Hotkey",
    enterOption: "Enter",
    shiftEnterOption: "Shift + Enter",
    ctrlEnterOption: "Ctrl + Enter",
    cmdEnterOption: "Cmd + Enter",
    showAds: "Show Ads",
    hideAds: "Hide Ads",
    close: "Close",
    downloadApps: "Download Apps",
    searchChats: "Search chats...",
    account: "Account",
    profileSubtitle: "Your profile & subscription",
    username: "Username",
    save: "Save",
    cancel: "Cancel",
    turnOffAds: "Turn Off Ads",
    turnOnAds: "Turn On Ads",
    themeDescription: "Choose your preferred theme",
    languageDescription: "Choose your preferred language",
    fontFamily: "Font Family",
    fontFamilyDescription: "Choose your preferred font",
    fontSize: "Font Size",
    fontSizeDescription: "Choose your preferred size",
    hotkeysTitle: "Hotkeys",
    hotkeysDescription: "Customize keyboard shortcuts",
    billing: "Billing",
    billingDescription: "Manage subscription & payments",
    privacy: "Privacy",
    privacyDescription: "Security & account protection",
    support: "Support",
    supportDescription: "Get help & contact us",
  },
  zh: {
    placeholder: "开始与 MornGPT 对话...",
    thinking: "思考中...",
    deepThinking: "深度思考进行中...",
    newChat: "新对话",
    general: "通用",
    guestUser: "访客用户",
    login: "登录",
    signOut: "退出登录",
    setting: "设置",
    share: "分享",
    copy: "复制",
    delete: "删除",
    deepThinkingBtn: "深度思考",
    creativeIdeasBtn: "创意想法",
    analyzeBtn: "分析",
    problemSolveBtn: "问题解决",
    uploadFiles: "上传文件",
    send: "发送",
    poweredBy: "由",
    noChatSelected: "未选择对话",
    noConversationToShare: "没有可分享的对话",
    signUpToShare: "注册以分享对话",
    shareConversation: "分享对话",
    guestSessionExpired: "由于不活动，您的访客会话已过期。您的对话已被清除。",
    textCopied: "文本已复制到剪贴板",
    textDeleted: "文本已删除",
    characters: "字符",
    dragToResize: "拖拽调整大小",
    shortcutsActive: "快捷键已启用",
    shortcutsDisabled: "快捷键已禁用",
    enabled: "已启用",
    disabled: "已禁用",
    newChatInGeneral: "在通用中新建对话",
    multiGPTDeepThinking: "多GPT深度思考",
    poweredByModel: "由 {model} 提供支持",
    rename: "重命名",
    deleteChat: "删除对话",
    exportChat: "导出对话",
    settings: "设置",
    shortcuts: "快捷键",
    theme: "主题",
    language: "语言",
    notifications: "通知",
    sound: "声音",
    autoSave: "自动保存",
    errorLoadingShared: "加载共享对话时出错。链接可能无效或已过期。",
    sharedConversationLoaded: '已加载共享对话："{title}" 由 {author} 创建',
    attachedFiles: "附件文件",
    maximumFilesReached: "已达到最大文件数 {count}。请先删除一些文件。",
    uploading: "上传中...",
    uploadFilesMax: "上传文件（最多 {count} 个，总计 {size}MB）",
    selectModel: "选择模型",
    external: "外部",
    mornGPT: "MornGPT",
    beSpecific: "明确您的目标",
    chooseSpecialized: "选择专门的 MornGPT 模型",
    uploadFilesWith: "上传文件",
    useCtrlEnter: "使用 Ctrl/Cmd + Enter",
    download: "下载",
    bookmark: "收藏",
    bookmarked: "已收藏",
    removeBookmark: "取消收藏",
    copyResponse: "复制回复",
    shareResponse: "分享回复",
    downloadResponse: "下载回复",
    bookmarkMessage: "收藏消息",
    heroTagline: "高级 AI 模型触手可及",
    searchConversations: "搜索对话...",
    searchBookmarks: "搜索书签...",
    searchPrompts: "搜索提示词...",
    recentPromptsHistory: "最近提示历史",
    noPromptsFound: "未找到提示",
    noRecentPrompts: "暂无提示历史",
    conversationTab: "对话",
    bookmarksTab: "书签",
    promptsTab: "提示词",
    jumpToConversation: "跳转到对话位置",
    noConversationsFound: "未找到对话",
    noConversationsYet: "还没有对话",
    youLabel: "你",
    aiLabel: "AI",
    bookmarkedMessages: "已收藏消息",
    exportBookmarks: "导出书签",
    importBookmarks: "导入书签",
    createFolder: "新建文件夹",
    noBookmarksFound: "未找到书签",
    noBookmarksYet: "还没有收藏的消息",
    settingsTitle: "设置",
    themeLabel: "主题",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    languageLabel: "语言",
    languageEnglish: "英语",
    languageChinese: "中文",
    notificationsLabel: "通知",
    soundLabel: "声音",
    autoSaveLabel: "自动保存",
    sendHotkeyLabel: "发送快捷键",
    enterOption: "回车",
    shiftEnterOption: "Shift + Enter",
    ctrlEnterOption: "Ctrl + Enter",
    cmdEnterOption: "Cmd + Enter",
    showAds: "显示广告",
    hideAds: "隐藏广告",
    close: "关闭",
    downloadApps: "下载客户端",
    searchChats: "搜索对话...",
    account: "账户",
    profileSubtitle: "个人资料与订阅",
    username: "用户名",
    save: "保存",
    cancel: "取消",
    turnOffAds: "关闭广告",
    turnOnAds: "打开广告",
    themeDescription: "选择你偏好的主题",
    languageDescription: "选择你偏好的语言",
    fontFamily: "字体",
    fontFamilyDescription: "选择偏好的字体",
    fontSize: "字号",
    fontSizeDescription: "选择偏好的字号",
    hotkeysTitle: "快捷键",
    hotkeysDescription: "自定义键盘快捷键",
    billing: "账单与订阅",
    billingDescription: "管理订阅与支付",
    privacy: "隐私与安全",
    privacyDescription: "安全与账号保护",
    support: "支持",
    supportDescription: "获取帮助与联系我们",
  },
};

export type TranslationKey = keyof typeof translations.en;

export function getLocalizedText(key: TranslationKey, language: string): string {
  const lang = language as keyof typeof translations;
  return translations[lang]?.[key] || translations.en[key] || key;
}

export function createLocalizedTextGetter(language: string) {
  return (key: TranslationKey) => getLocalizedText(key, language);
}
